"""
pricing.py — the margin gate. SOLVENT's core economic discipline.

Before accepting any job, the agent estimates what the job will COST it to
fulfil (compute + data + SaaS) and what it can PRICE the job at. If the
projected margin does not clear the floor, the agent declines the work.

This is the feature that makes SOLVENT a *business* and not just a bot: it is
structurally incapable of working at a loss.

Declining is not the end of the conversation, though. A shop that only ever
says "no" leaves money on the table, so every decline also carries a
**counter-offer**: either the price at which the agent *would* take the work,
or a narrower scope it can deliver inside the customer's existing budget.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

# Estimated cost of each resource the analyst might consume, in cents.
# These are the prices SOLVENT pays its own vendors (see stripe_client.spend).
RESOURCE_COSTS_CENTS: dict[str, int] = {
    "nemotron_tokens_per_1k": 30,  # NVIDIA Nemotron inference
    "market_data_call": 120,  # market-data-api per pull
    "web_search_call": 8,  # web-search-api per query
    "pdf_render": 40,  # pdf-render-saas per report
    "email_send": 5,  # email-delivery-saas per delivery
}


@dataclass
class Quote:
    """Represents a job quote generated by the margin gate.

    Attributes:
        price_cents: The price quoted to the client (equal to client's budget).
        est_cost_cents: The estimated fulfillment cost in cents.
        margin_cents: The projected profit margin in cents.
        margin_pct: The projected profit margin percentage.
        accept: True if the job is accepted, False if declined.
        reason: Explanatory text for the decision.
        cost_breakdown: Itemized dictionary of estimated vendor costs.
        counter_offer: On a decline, the deal the agent *would* accept
            (see :func:`counter_offer`). ``None`` when the job was accepted or
            when no viable alternative exists.
    """

    price_cents: int
    est_cost_cents: int
    margin_cents: int
    margin_pct: float
    accept: bool
    reason: str
    cost_breakdown: dict[str, int]
    counter_offer: dict[str, Any] | None = None


@dataclass
class PricingPolicy:
    """Pricing rules governing the margin gate.

    Attributes:
        margin_floor_pct: The minimum profit margin required to accept a job.
        min_price_cents: The minimum price (order size) in cents for any job.
    """

    margin_floor_pct: float = 35.0  # refuse jobs under this projected margin
    min_price_cents: int = 1_500  # never sell a report under $15
    #: Floor scope for a counter-offer: the thinnest brief still worth selling.
    min_scope: dict[str, int] = field(
        default_factory=lambda: {
            "est_tokens": 4_000,
            "market_data_calls": 0,
            "web_search_calls": 3,
        }
    )


def get_resource_costs() -> dict[str, int]:
    """Return effective resource costs, applying ``pricing_overrides.json`` if present.

    The override file is resolved under :func:`solvent.paths.config_dir`, so
    the cost model does not change depending on the working directory.
    """
    import json

    from .paths import config_path

    costs = dict(RESOURCE_COSTS_CENTS)
    override_path = config_path("pricing_overrides.json")
    if override_path.is_file():
        try:
            overrides = json.loads(override_path.read_text(encoding="utf-8"))
            if isinstance(overrides, dict):
                for k, v in overrides.items():
                    if k in costs and isinstance(v, (int, float)):
                        costs[k] = int(v)
        except (json.JSONDecodeError, OSError):
            pass
    return costs


def estimate_cost(job: dict[str, Any]) -> tuple[int, dict[str, int]]:
    """Estimate fulfilment cost from the job's declared complexity."""
    costs = get_resource_costs()
    tokens_k = job.get("est_tokens", 8_000) / 1_000
    breakdown = {
        "nemotron_inference": round(tokens_k * costs["nemotron_tokens_per_1k"]),
        "market_data": job.get("market_data_calls", 2) * costs["market_data_call"],
        "web_search": job.get("web_search_calls", 6) * costs["web_search_call"],
        "pdf_render": costs["pdf_render"],
        "email_send": costs["email_send"],
    }
    return sum(breakdown.values()), breakdown


#: Unit cost of one step of each scope dimension, most expensive first. A
#: counter-offer gives up the priciest resource before touching the cheap ones,
#: so the narrowed brief keeps as much substance per cent as it can.
_SCOPE_STEPS: tuple[tuple[str, int], ...] = (
    ("market_data_calls", 1),
    ("est_tokens", 1_000),
    ("web_search_calls", 1),
)


def job_scope(job: dict[str, Any]) -> dict[str, int]:
    """The three resource dials a brief can be scoped on, with defaults filled in."""
    return {
        "est_tokens": int(job.get("est_tokens", 8_000)),
        "market_data_calls": int(job.get("market_data_calls", 2)),
        "web_search_calls": int(job.get("web_search_calls", 6)),
    }


def min_viable_price_cents(est_cost_cents: int, policy: PricingPolicy | None = None) -> int | None:
    """The lowest whole-dollar price that clears both the margin floor and the minimum order size.

    Returns ``None`` when the margin floor is 100% or higher, where no finite
    price can ever clear it.
    """
    applied = policy or PricingPolicy()
    if applied.margin_floor_pct >= 100:
        return None
    required = est_cost_cents / (1 - applied.margin_floor_pct / 100)
    price = max(math.ceil(required), applied.min_price_cents)
    # Quote in whole dollars — rounding up only widens the margin.
    return math.ceil(price / 100) * 100


def scoped_alternative(
    job: dict[str, Any], policy: PricingPolicy | None = None
) -> tuple[dict[str, int], Quote] | None:
    """Find the richest narrowed scope this job's budget *can* buy.

    Resources are given up one step at a time, priciest dimension first, until
    the margin gate accepts the job at the customer's own budget. Returns the
    winning scope and its quote, or ``None`` if even the floor scope is
    unaffordable (or the budget is below the minimum order size, where no
    amount of narrowing helps).
    """
    applied = policy or PricingPolicy()
    budget = int(job.get("budget_cents", 0) or 0)
    if budget < applied.min_price_cents:
        return None

    scope = job_scope(job)
    floor = {**PricingPolicy().min_scope, **applied.min_scope}

    while True:
        trial = quote({**job, **scope}, applied, with_counter_offer=False)
        if trial.accept:
            return scope, trial
        for dimension, step in _SCOPE_STEPS:
            if scope[dimension] - step >= floor.get(dimension, 0):
                scope = {**scope, dimension: scope[dimension] - step}
                break
        else:
            return None  # already at the floor scope and still unprofitable


def counter_offer(
    job: dict[str, Any], policy: PricingPolicy | None = None
) -> dict[str, Any] | None:
    """Build the deal the agent *would* accept for a job it just declined.

    Two shapes, in order of preference:

    * ``scope`` — a narrower brief that fits the customer's existing budget.
      Nobody has to find more money, so this is offered first.
    * ``price`` — the same brief at the lowest price that clears the margin
      floor, for when no sellable scope fits the budget.

    Returns ``None`` when neither is possible.
    """
    applied = policy or PricingPolicy()
    budget = int(job.get("budget_cents", 0) or 0)

    alternative = scoped_alternative(job, applied)
    if alternative is not None:
        scope, scoped_quote = alternative
        current = job_scope(job)
        changes = {k: v for k, v in scope.items() if current[k] != v}
        return {
            "kind": "scope",
            "price_cents": scoped_quote.price_cents,
            "est_cost_cents": scoped_quote.est_cost_cents,
            "margin_pct": scoped_quote.margin_pct,
            "scope": scope,
            "scope_changes": changes,
            "message": (
                f"can deliver a narrower brief for ${budget / 100:.2f} ({_describe_scope(changes)})"
            ),
        }

    est_cost, _ = estimate_cost(job)
    price = min_viable_price_cents(est_cost, applied)
    if price is None or price <= budget:
        return None
    priced = quote({**job, "budget_cents": price}, applied, with_counter_offer=False)
    if not priced.accept:
        return None
    return {
        "kind": "price",
        "price_cents": price,
        "est_cost_cents": priced.est_cost_cents,
        "margin_pct": priced.margin_pct,
        "scope": None,
        "scope_changes": {},
        "message": f"can deliver this brief as specified for ${price / 100:.2f}",
    }


def _describe_scope(changes: dict[str, int]) -> str:
    labels = {
        "est_tokens": "tokens",
        "market_data_calls": "market-data pulls",
        "web_search_calls": "web searches",
    }
    if not changes:
        return "same scope"
    return ", ".join(f"{labels.get(k, k)} → {v:,}" for k, v in changes.items())


def quote(
    job: dict[str, Any],
    policy: PricingPolicy | None = None,
    *,
    with_counter_offer: bool = True,
) -> Quote:
    """Evaluate if a job's budget is acceptable according to the pricing policy.

    The budget is treated as the target price. The function checks whether this price
    satisfies the minimum price requirement and the margin floor.

    Args:
        job: A dictionary containing the job details (e.g. budget_cents).
        policy: The pricing policy to apply. Defaults to a new PricingPolicy instance.
        with_counter_offer: Attach a counter-offer to a declined quote. Set
            ``False`` for the internal evaluations that build those offers.

    Returns:
        A Quote object indicating whether the job was accepted or rejected.
    """
    applied_policy = policy or PricingPolicy()
    est_cost, breakdown = estimate_cost(job)

    # We can never charge more than the customer is willing to pay, so the
    # budget IS the price. The gate then decides whether that price clears
    # both the minimum order size and the margin floor.
    budget = job.get("budget_cents", 0)
    price = budget

    margin = price - est_cost
    margin_pct = round(100 * margin / price, 1) if price else -100.0

    def _decline(reason: str) -> Quote:
        declined = Quote(price, est_cost, margin, margin_pct, False, reason, breakdown)
        if with_counter_offer:
            declined.counter_offer = counter_offer(job, applied_policy)
        return declined

    if budget < applied_policy.min_price_cents:
        return _decline(
            f"order ${budget / 100:.0f} below minimum order size "
            f"${applied_policy.min_price_cents / 100:.0f}"
        )
    if budget < est_cost:
        return _decline("customer budget below fulfilment cost")
    if margin_pct < applied_policy.margin_floor_pct:
        return _decline(
            f"projected margin {margin_pct}% below floor {applied_policy.margin_floor_pct}%"
        )
    return Quote(price, est_cost, margin, margin_pct, True, "accepted", breakdown)
